import { StockItem, Store } from "./lib/schema/inventory";
import { uniqueId } from "./lib/utils";
import { AddOn, MenuItem, PairedItem } from "./types/menu";
import { Product } from "@/lib/schema/market";

export const demoAddOns: AddOn[] = [
  {
    id: uniqueId(),
    name: "Plantain",
    price: 500,
    image: "/images/food/plantain.jpg",
  },
  {
    id: uniqueId(),
    name: "ColeSlaw",
    price: 1000,
    image: "/images/food/coleslaw.jpeg",
  },
];

export const demoPairedItems: PairedItem[] = [
  {
    id: uniqueId(),
    name: "Pepsi",
    price: 400,
    image: "/images/food/pepsi.jpg",
  },
  {
    id: uniqueId(),
    name: "Coke",
    price: 450,
    image: "/images/food/coke.jpg",
  },
];

export const demoMenuItems: MenuItem[] = [
  {
    id: uniqueId(),
    price: 1000,
    name: "Jollof Rice",
    category: "Rice Dishes",
    status: "available",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-1.png",
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
  {
    id: uniqueId(),
    name: "Fried Rice",
    price: 1200,
    category: "Rice Dishes",
    status: "unlisted",
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-2.png",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
  {
    id: uniqueId(),
    name: "Grilled Fish with Fried Plantain",
    price: 2500,
    category: "Grills & BBQ",
    status: "available",
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-3.png",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
  {
    id: uniqueId(),
    name: "BBQ Chicken Thighs",
    price: 2000,
    category: "Grills & BBQ",
    status: "unlisted",
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-4.png",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
  {
    id: uniqueId(),
    name: "BBQ Chicken Drumsticks",
    price: 1500,
    category: "Grills & BBQ",
    status: "available",
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-5.png",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
];

export const demoStores: Store[] = [
  {
    id: "default",
    name: "Stores",
    description: "Default store created by the system",
    image: "/images/store/store-1.png",
  },
  {
    id: "chicken-hotspot",
    name: "Chicken Hotspot",
    description: "Your go-to spot for chicken and frozen foods",
    image: "/images/store/store-2.png",
  },
];

export const demoStockItems: StockItem[] = [
  {
    id: uniqueId(),
    name: "Frozen Chicken Wings",
    store: demoStores[1].id,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830538/chicken-wings_wm9ndr.png",
    expirationDate: { month: 12, year: 2025 },
    measuringUnit: "kg",
    lowStockThreshold: 5,
    category: "Frozen Foods",
    purchasePrice: 1500,
    quantity: 10,
  },
  {
    id: uniqueId(),
    name: "Frozen Chicken Drumsticks",
    store: demoStores[1].id,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830511/chicken-drumsticks_lgt2x1.png",
    expirationDate: { month: 12, year: 2025 },
    measuringUnit: "kg",
    lowStockThreshold: 5,
    category: "Frozen Foods",
    purchasePrice: 1500,
    quantity: 10,
  },
  {
    id: uniqueId(),
    name: "Frozen Chicken Thighs",
    store: demoStores[1].id,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830527/chicken-thighs_ozzkgd.png",
    expirationDate: { month: 12, year: 2025 },
    measuringUnit: "kg",
    lowStockThreshold: 5,
    category: "Frozen Foods",
    purchasePrice: 1500,
    quantity: 10,
  },
  {
    id: uniqueId(),
    name: "Frozen Chicken Breast",
    store: demoStores[1].id,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830485/chicken-breast_rm3h6j.png",
    expirationDate: { month: 12, year: 2025 },
    measuringUnit: "kg",
    lowStockThreshold: 5,
    category: "Frozen Foods",
    purchasePrice: 1500,
    quantity: 10,
  },
];

export const demoProducts: Product[] = [
  {
    id: uniqueId(),
    name: "Mama Gold Rice",
    brand: "FMN (Flour Mills of Nigeria)",
    category: "Grain Products",
    description:
      "Premium quality Nigerian grown parboiled rice with natural nutritious and healthy components which is specifically processed with high quality grains.",
    price: 115000,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830739/mama-gold-rice_kqdkfv.png",
    inStock: true,
    rating: 4.8,
    quantity: 50,
    manufacturerName: "Flour Mills of Nigeria",
    reviews: [
      {
        id: uniqueId(),
        userId: "user1",
        rating: 5,
        comment: "Great quality, best rice I've used in a long time",
        verified: true,
        date: new Date("2024-01-15"),
      },
    ],
  },
  {
    id: uniqueId(),
    name: "Golden Penny Pasta",
    brand: "Golden Penny",
    category: "Pasta & Noodles",
    description:
      "High-quality pasta made from durum wheat, perfect for all your pasta dishes.",
    price: 8500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830338/spag_bybr4z.png",
    inStock: true,
    rating: 4.6,
    quantity: 100,
    manufacturerName: "Flour Mills of Nigeria",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Peak Full Cream Milk Powder",
    brand: "Peak",
    category: "Dairy Products",
    description:
      "Nutritious full cream milk powder, fortified with essential vitamins and minerals.",
    price: 12500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830769/peak-milk_ais9hw.jpg",
    inStock: true,
    rating: 4.7,
    quantity: 75,
    manufacturerName: "FrieslandCampina WAMCO Nigeria",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Kings Vegetable Oil",
    brand: "Kings",
    category: "Cooking Oils",
    description: "Pure vegetable oil, perfect for all your cooking needs.",
    price: 45000,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830667/kings-oil_jt9wvi.jpg",
    inStock: true,
    rating: 4.5,
    quantity: 30,
    manufacturerName: "Kings Oil Nigeria",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Dangote Sugar",
    brand: "Dangote",
    category: "Baking Supplies",
    description: "Fine granulated sugar, perfect for baking and everyday use.",
    price: 7500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830586/dangote-sugar_qpwbpe.jpg",
    inStock: true,
    rating: 4.4,
    quantity: 200,
    manufacturerName: "Dangote Sugar Refinery",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Knorr Chicken Cubes",
    brand: "Knorr",
    category: "Seasonings",
    description: "Rich chicken flavor seasoning cubes for delicious meals.",
    price: 2500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830676/knorr-cubes_itt6u3.jpg",
    inStock: true,
    rating: 4.8,
    quantity: 150,
    manufacturerName: "Unilever Nigeria",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Indomie Instant Noodles (Carton)",
    brand: "Indomie",
    category: "Pasta & Noodles",
    description:
      "Nigeria's favorite instant noodles, available in various flavors.",
    price: 35000,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830651/indomie-carton_u8jpjq.jpg",
    inStock: true,
    rating: 4.9,
    quantity: 40,
    manufacturerName: "Dufil Prima Foods",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Titus Sardines",
    brand: "Titus",
    category: "Canned Foods",
    description: "Premium sardines in tomato sauce, rich in omega-3.",
    price: 9500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830832/titus-sardines_k6aewr.jpg",
    inStock: false,
    rating: 4.6,
    quantity: 0,
    manufacturerName: "CFAO Nigeria",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Milo Energy Drink Powder",
    brand: "Milo",
    category: "Beverages",
    description:
      "Chocolate and malt beverage powder, enriched with vitamins and minerals.",
    price: 15000,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830721/milo-tin_srbhv3.jpg",
    inStock: true,
    rating: 4.8,
    quantity: 60,
    manufacturerName: "Nestlé Nigeria",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Honeywell Wheat Flour",
    brand: "Honeywell",
    category: "Baking Supplies",
    description: "Premium quality wheat flour for all your baking needs.",
    price: 32000,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830636/honeywell-flour_uft7ue.png",
    inStock: true,
    rating: 4.5,
    quantity: 45,
    manufacturerName: "Honeywell Flour Mills",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Power Oil",
    brand: "Power",
    category: "Cooking Oils",
    description:
      "Healthy vegetable oil, cholesterol-free and vitamin-fortified.",
    price: 42000,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737833651/power-oil_xdbmjl.jpg",
    inStock: true,
    rating: 4.7,
    quantity: 35,
    manufacturerName: "Dufil Prima Foods",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Golden Penny Semovita",
    brand: "Golden Penny",
    category: "Grain Products",
    description: "Fine semolina flour for making smooth semovita.",
    price: 18500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830628/golden-penny-semovita_dkuat1.jpg",
    inStock: true,
    rating: 4.6,
    quantity: 80,
    manufacturerName: "Flour Mills of Nigeria",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Dano Full Cream Milk Powder",
    brand: "Dano",
    category: "Dairy Products",
    description: "Rich and creamy milk powder for all your dairy needs.",
    price: 11500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830591/dano-milk_gqkgqj.jpg",
    inStock: true,
    rating: 4.4,
    quantity: 65,
    manufacturerName: "Arla Foods",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Devon Kings Margarine",
    brand: "Devon Kings",
    category: "Dairy Products",
    description: "Smooth and creamy margarine for bread and baking.",
    price: 5500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830600/devon-kings-margarine_bgaczs.jpg",
    inStock: true,
    rating: 4.3,
    quantity: 90,
    manufacturerName: "PZ Wilmar",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Mamador Cooking Oil",
    brand: "Mamador",
    category: "Cooking Oils",
    description: "Premium cooking oil for healthy and tasty meals.",
    price: 43500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830685/mamador-oil_bvcitu.jpg",
    inStock: true,
    rating: 4.6,
    quantity: 40,
    manufacturerName: "PZ Wilmar",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Three Crown Milk Powder",
    brand: "Three Crown",
    category: "Dairy Products",
    description: "Nutrient-rich milk powder for the whole family.",
    price: 11000,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830822/three-crown-milk_l1y2ki.jpg",
    inStock: true,
    rating: 4.5,
    quantity: 70,
    manufacturerName: "FrieslandCampina WAMCO Nigeria",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Gino Tomato Paste",
    brand: "Gino",
    category: "Canned Foods",
    description: "Rich and thick tomato paste for delicious stews and sauces.",
    price: 4500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830606/gino-tomato_k1csji.jpg",
    inStock: true,
    rating: 4.7,
    quantity: 120,
    manufacturerName: "GB Foods",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Bama Mayonnaise",
    brand: "Bama",
    category: "Condiments",
    description: "Creamy mayonnaise for sandwiches and salads.",
    price: 6500,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830579/bama-mayo_shygdu.jpg",
    inStock: true,
    rating: 4.6,
    quantity: 85,
    manufacturerName: "GBfoods Africa",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Olam Rice",
    brand: "Olam",
    category: "Grain Products",
    description: "Premium quality rice grown and processed in Nigeria.",
    price: 95000,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830777/olam-rice_iyqvgs.jpg",
    inStock: true,
    rating: 4.5,
    quantity: 55,
    manufacturerName: "Olam Nigeria",
    reviews: [],
  },
  {
    id: uniqueId(),
    name: "Terra Seasoning Cubes",
    brand: "Terra",
    category: "Seasonings",
    description: "Rich flavor seasoning cubes for all your cooking needs.",
    price: 2200,
    image: "https://res.cloudinary.com/daf7mvn2b/image/upload/v1737830808/terra-cubes_b1tb8x.jpg",
    inStock: true,
    rating: 4.3,
    quantity: 180,
    manufacturerName: "TGI Group",
    reviews: [],
  },
];

export const productCategories: Set<string> = new Set();

for (const p of demoProducts) {
  productCategories.add(p.category);
}
